import Head from "next/head";
import { CategoryRow } from "./CategoryRow";
import { NavBar } from "./NavBar";

export default function Page({ categorie, currentPage, titlePage }) {
	return (
		<div>
			<Head>
				<title>Movie App{titlePage}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="md:px-9 sm:px-7 px-4 py-4 App">
				<NavBar currentPage={currentPage} />

				{categorie.map(({ title, path }) => (
					<CategoryRow key={title} title={title} path={path} />
				))}
			</div>
		</div>
	);
}
