import Head from "next/head";
import { CategoryRow } from "./CategoryRow";
import { NavBar } from "./NavBar";
import Skeleton from "./Skeleton";

export default function Page({ categorie, currentPage, titlePage }) {
	const categoryRowSkeleton = [1, 2, 3];

	for (let i = 0; i < 2; i++) {
		categoryRowSkeleton.push("");
	}

	return (
		<>
			<Head>
				<title>{titlePage}Movie App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="md:px-9 sm:px-7 px-4 py-4 App">
				<NavBar currentPage={currentPage} />

				{categorie.map(({ title, path }) => (
					<CategoryRow key={title} title={title} path={path} />
				))}
			</div>
		</>
	);
}
