import Head from "next/head";
import { CategoryRow } from "../components/CategoryRow";
import { categories } from "../services/api";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Movie App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet" />
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
				/>
			</Head>

			<div className="md:px-9 sm:px-7 px-4 py-4">
				<header className="  text-amber-300 flex justify-center">
					<h1 className=" flex justify-center md:text-8xl sm:text-6xl text-5xl font-bold tracking-wider">
						MOVIE APP
					</h1>
				</header>

				{categories.map(({ title, path }) => (
					<CategoryRow key={title} title={title} path={path} />
				))}
			</div>
		</div>
	);
}
