import Head from "next/head";
import { useEffect, useState } from "react";
import { MovieCard } from "../components/MovieCard";
import { NavBar } from "../components/NavBar";
import { apiKey } from "./api/services/api";

let currentPager = 1;
let totalPages;
let indexSearch = true;
export default function Search() {
	const [inputSearchValue, useInputSearchValue] = useState("");
	const [searchData, setSearchData] = useState();

	const [currentPage, setCurrentPage] = useState(1);
	async function execFetch(url) {
		const data = await fetch(url)
			.then((res) => res.json())
			.catch((err) => console.log(`Erro: ${err}`));
		totalPages = data.total_pages;
		setSearchData(data.results);
	}

	useEffect(() => {
		currentPager = 1;
		setCurrentPage(currentPager);
		if (inputSearchValue != "") {
			setTimeout(() => {
				indexSearch = false;
				execFetch(
					`https://api.themoviedb.org/3/search/multi?api_key=${apiKey}&language=pt-BR&query=${inputSearchValue}&page=${currentPage}`
				);
			}, 1000);
		} else {
			indexSearch = true;
			execFetch(`https://api.themoviedb.org/3/trending/all/week?api_key=${apiKey}&language=pt-BR`);
		}
	}, [inputSearchValue]);

	function handleInput(e) {
		useInputSearchValue(e.target.value);
	}

	async function loadingMoreData() {
		currentPager++;
		setCurrentPage(currentPager);

		const url = !indexSearch
			? `https://api.themoviedb.org/3/search/multi?api_key=${apiKey}&language=pt-BR&query=${inputSearchValue}&page=${currentPager}`
			: `https://api.themoviedb.org/3/trending/all/week?api_key=${apiKey}&language=pt-BR&page=${currentPager}`;

		const data = await fetch(url).then((res) => res.json());

		setSearchData([...searchData, ...data.results]);
	}

	return (
		<>
			<Head>
				<title>Pesquisar - Movie App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="md:px-9 sm:px-7 px-4 py-4 App">
				<NavBar currentPage={"search"} />
				<div className="flex justify-center items-center pb-7">
					<input
						className=" text-sm lg:text-base  px-2 py-1 text-white sm:w-[400px] w-3/4 bg-transparent border-2 border-amber-300 rounded-md outline-0"
						placeholder="Pesquise seu filme ou série aqui"
						onChange={handleInput}
						value={inputSearchValue}
						type="text"
					/>
				</div>

				<main className="grid gap-5 grid-search place-items-center">
					{searchData ? (
						searchData.map(({ id, title, poster_path }, index) => (
							<MovieCard key={`${id}${index}`} id={id} title={title} imageUrl={poster_path} />
						))
					) : (
						<></>
					)}
				</main>

				{totalPages > 1 && currentPage < totalPages ? (
					<div className="flex justify-center items-center mt-10">
						<button
							onClick={loadingMoreData}
							className="bg-amber-300 rounded-md p-2 sm:hover:bg-transparent sm:hover:text-white border-2 border-amber-300 transition duration-300 "
						>
							Carregar mais
						</button>
					</div>
				) : (
					false
				)}
			</div>
		</>
	);
}
